### ISSUE TITLE
Разработать метод для автоматизирования проверки отчетов

### ISSUE THREAD

**Issue by KoprovDmitry** [Students-of-the-city-of-Kostroma/TPRO#2]
Разработать метод для автоматизирования проверки отчетов по [правилу](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/issue-1344/Docs/Contributers/UserStory)

**Comment by KoprovDmitry** [comment]
Можете скинуть прямую ссылку на "отчет", чтобы проверять корректность работы метода?
Ветку для проверки правильности написания отчета я нашел, [issue-1361](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1361)

**Comment by YuriSilenok** [comment]
Смотрите [здесь](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/issue-1344/Docs/Contributers/UserStory).

**Comment by KoprovDmitry** [comment]
Я думаю, что с методом check_user_story работа почти закончена, могу узнать что должен делать данный метод при отсутствии ошибок в отчете?

**Comment by KoprovDmitry** [comment]
[пользовательская история для тестирования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1372/files), для себя и чтобы не потерять

**Comment by KoprovDmitry** [comment]
Протестировал [этот текст](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1372/files) и следуя [правилам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/issue-1344/Docs/Contributers/UserStory) нашел несколько [ошибок](https://prnt.sc/v6z9ii)

**Comment by YuriSilenok** [comment]
> Протестировал [этот текст](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1372/files) и следуя [правилам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/issue-1344/Docs/Contributers/UserStory) нашел несколько [ошибок](https://prnt.sc/v6z9ii)

давайте попробуем внедрять вас скрипт в работу.

**Comment by YuriSilenok** [comment]
но тем не менее, моя задача научить Вас работать с таск-менеджером.
И у меня большие претензии к заголовку задачи и запроса, а так же к том, кто ответственен за эти запрос и задачу, а так же кто проверяет запрос

**Comment by KoprovDmitry** [comment]
исправил

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/97801114-6eaeb380-1c4b-11eb-88e0-473acc261452.png)
У вас синтаксические ошибки в коде

**Comment by KoprovDmitry** [comment]
исправил

**Comment by YuriSilenok** [comment]
Я оькатил изменения, так как синтаксические ошибки присутствовали в мастере после вашего мержа

**Comment by KoprovDmitry** [comment]
синтаксические ошибки [такие же](https://user-images.githubusercontent.com/14871471/97801114-6eaeb380-1c4b-11eb-88e0-473acc261452.png) или другие?

**Comment by YuriSilenok** [comment]
У Вас не определен метод `add_failing_comment` 
![image](https://user-images.githubusercontent.com/14871471/99946161-f4270e80-2d86-11eb-9561-7d1f8ada5c8c.png)
